# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-10 09:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20160910_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameseed',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
