# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-10 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20160910_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameseed',
            name='game_type',
            field=models.IntegerField(choices=[(1, 'code words')], default=1),
        ),
    ]
